name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: geode-sdk/build-geode-mod@main
